stages:
    - test
    - build
    - deploy

run_tests:
    stage: test
    image: python:3.10.8-slim-buster
    before_script:
        - pip install -r app/requirements.txt
    script:
        - python3 tests/test.py

build_image:
    stage: build
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"

    before_script:
        - cd app/
    script:
        - docker login -u $username -p $password
        - docker build -t prathik98/demo:latest .
        - docker push prathik98/demo:latest
deploy_image:
    stage: deploy
    before_script:
        - chmod 400 $SSH_KEY
    script:
        - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@52.12.53.176 "
            docker login -u $username -p $password &&
            docker ps -q --filter status=running | xargs -r docker stop &&
            docker ps -q --filter status=exited | xargs -r docker rm &&
            docker images -q | xargs docker rmi &&
            docker run --rm -d --network host prathik98/demo:latest"
            # ubuntu@publicIP (public IP should be static - elastic setting) - EC2 instance
            # corresponding PEM file in gitlab system variables
